-- permissions 테이블의 feature ENUM에 DEVICE_INSPECTION 추가
ALTER TABLE permissions MODIFY COLUMN feature ENUM('DEVICE_LIST','DEVICE_MANAGEMENT','DEVICE_INSPECTION','SCHOOL_MANAGEMENT','CLASSROOM_MANAGEMENT','FLOORPLAN_MANAGEMENT','DATA_DELETE','WIRELESS_AP_LIST','WIRELESS_AP_MANAGEMENT','SUBMISSION_FILES','QR_CODE_GENERATION') NOT NULL;
